# Generated by Django 6.0.2 on 2026-02-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtualoffice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingroom",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="meeting_rooms/"),
        ),
        migrations.AddField(
            model_name="meetingroom",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="package",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="packages/"),
        ),
        migrations.AddField(
            model_name="package",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
