# Generated by Django 6.0.2 on 2026-02-25 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "virtualoffice",
            "0002_meetingroom_image_meetingroom_slug_package_image_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Paket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("harga", models.DecimalField(decimal_places=0, max_digits=12)),
                ("deskripsi", models.TextField()),
                (
                    "gambar",
                    models.ImageField(blank=True, null=True, upload_to="paket/"),
                ),
                ("pengelolaan_surat", models.BooleanField(default=False)),
                ("jam_meeting", models.IntegerField(default=0)),
                ("telepon_khusus", models.BooleanField(default=False)),
                ("layanan_prioritas", models.BooleanField(default=False)),
                ("aktif", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pertanyaan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("nomor_hp", models.CharField(max_length=20)),
                ("pesan", models.TextField(blank=True)),
                ("dibuat_pada", models.DateTimeField(auto_now_add=True)),
                (
                    "paket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="virtualoffice.paket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RuangRapat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("harga_per_jam", models.DecimalField(decimal_places=0, max_digits=12)),
                ("deskripsi", models.TextField()),
                ("kapasitas", models.IntegerField(default=0)),
                (
                    "gambar",
                    models.ImageField(blank=True, null=True, upload_to="ruang_rapat/"),
                ),
                ("aktif", models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="inquiry",
            name="package",
        ),
        migrations.DeleteModel(
            name="MeetingRoom",
        ),
        migrations.DeleteModel(
            name="Inquiry",
        ),
        migrations.DeleteModel(
            name="Package",
        ),
    ]
