# Generated by Django 6.0.2 on 2026-02-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "virtualoffice",
            "0003_paket_pertanyaan_ruangrapat_remove_inquiry_package_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Coworking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("harga", models.DecimalField(decimal_places=0, max_digits=12)),
                ("deskripsi", models.TextField()),
                (
                    "tipe",
                    models.CharField(
                        choices=[
                            ("harian", "Harian"),
                            ("bulanan", "Bulanan"),
                            ("dedicated", "Dedicated Desk"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "gambar",
                    models.ImageField(blank=True, null=True, upload_to="coworking/"),
                ),
                ("aktif", models.BooleanField(default=True)),
            ],
        ),
    ]
