# Generated by Django 6.0.2 on 2026-02-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtualoffice", "0004_coworking"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("paket", "Paket"),
                            ("meeting", "Ruang Rapat"),
                            ("coworking", "Coworking"),
                        ],
                        max_length=20,
                    ),
                ),
                ("product_id", models.IntegerField()),
                ("nama_perusahaan", models.CharField(max_length=255)),
                ("durasi", models.PositiveIntegerField()),
                ("total_harga", models.DecimalField(decimal_places=2, max_digits=15)),
                ("dibuat_pada", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
