# Generated by Django 6.0.2 on 2026-02-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtualoffice", "0005_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("min_durasi", models.PositiveIntegerField()),
                ("diskon_persen", models.DecimalField(decimal_places=2, max_digits=5)),
                ("aktif", models.BooleanField(default=True)),
                ("mulai", models.DateField(blank=True, null=True)),
                ("selesai", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
