# Generated by Django 6.0.2 on 2026-02-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtualoffice", "0006_promo"),
    ]

    operations = [
        migrations.AddField(
            model_name="paket",
            name="alamat_bisnis",
            field=models.BooleanField(default=False),
        ),
    ]
