# Generated by Django 6.0.2 on 2026-02-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtualoffice", "0007_paket_alamat_bisnis"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="alamat_perusahaan",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="email_perusahaan",
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="nama_penanggung_jawab",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="no_wa_penanggung_jawab",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="no_wa_perusahaan",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("contacted", "Contacted"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                ],
                default="initiated",
                max_length=20,
            ),
        ),
    ]
